apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-password
stringData:
  grafana-admin-password-secret: ENC[AES256_GCM,data:ewV6FApFokw=,iv:uG0yJNKIxvogaANU6BslOoqfhoukKaINS/A8MXcKkxU=,tag:pjtQCkbP5HqhgUuhqBb6nw==,type:str]
sops:
  age:
    - recipient: age1ezazx7ck5002pq8qkla2lytrrtfq5hqn9xlwl7wc0ea43qjdle4sllf2g9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRM0p5ZDRyNnBzeWhiVGx1
        M1drRS8vZzFSbVFNeitvdFc3MmVSdEJDMHdVClpnSEdlNGxsVFVHSlh3b2kvN1Fz
        SkIrRUtiZnVSMjZRMm1vTE1PSm9qblkKLS0tIDZaaXl3ZVJqN1c3V1lzUyt1VnRE
        YUhjUm9xcUNZdzVIdGJZcTNIWTh1K3MKf9sW6ECWicgHZxwlLboDxS5DrL0y9QBT
        tXBV3Ho5hp8jA3zdOKjPhDGY/AVZOLzUhOSfTK1FikjgoP9n87Gzcw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-07T11:01:50Z"
  mac: ENC[AES256_GCM,data:PFHHF2YMaoLTD+xe/yjri9fud7yCkqZrTtpDaBqBPdity+DvA4kqd+bbFkUHaw8WQvNbxuAOvdHJIdv4e8K00yDVUo5PQrUSFhE5LXSy6tr6rV8U4SOwG8cQ570yvfQYmOMS0s9+IuuGxpWR9ovT4NY8L98Avtkysfdd8+t9lVE=,iv:rnJ07SQa3n+9RrcgEEFUD0b/6/Scy2hdLtQhQkU/+M4=,tag:LzJlboB1qC+8M3y8xV3urA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
