---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: &name innogeoint
spec:
  hostnames:
    - "innogeoint.${SECRET_DOMAIN}"
  parentRefs:
    - name: envoy-external
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - name: *name
          namespace: default
          port: 8000
