apiVersion: v1
kind: Secret
metadata:
  name: truenas-iscsi-secret-config
stringData:
  driver-config-file.yaml: ENC[AES256_GCM,data:yNT8OnvEr6qucuDQW8DNN4WNkpm220mk76yvV5/8GmD3REVLxLQr/VdKz+FHV3BQ6sm4nL/PunVRee7qOG/RCdISmnuAlTk7PizcnBZJK0QJCbqE0DZtM0xCKY8KHZGqt9BjLmmruCeF4DggiFyNuO9j9/nNlMr9Sj8GI3UGxLlft5boTxqzAH5M7AAkmiz0pBM7zjVK+fFUDVX4n1ffPGcPs2HN7Uz4zdtb/kQt+Ulx/YylKaloGm7aKpBm31LHuF9Z6DLO0TM23V60BDpaLUkhcIPXm1vp0EIOvJU9Ouq5aKyUYwJ8RQa2f8tgotu2z7zfdKtnh/CxOtvB6524epwmxCpRbt/GUvMRn1D0Uiv5ImlZnOpFDNh/Ct+60hDUxRkWmymTPYMggHslKBmAAUELe+o1Wu8MdkTlPNp60SyT1Hhts2fmsyqSFrDcLc9K+N+HV9K3up9owT7AhyKsUv0KCK5hqzBDuPknT/IefptV4tMcSXDN8354SxXl9JwVtVRPIzq4PFDFbGXtlMZT2NmUNaN9f72x7/P2kSzI9994lWMY5DG7LCPp0Sen8aWhpw9T/47QKOBk7tjxpZpAae2f6XGwijkiPdEJtds1XfuLHxrKjGQF/PGwSgJ4EgaAR47xECV1xV5V/FldFIfvlpQzV1mvlRV7tTLRlqztCdBwn82X/84+3L2FNQjHeroQP68FzvOWuLrC17ZAx0im95C4VtU0D/eyM0EMWCJ0+PCmIyDiWSUnNe8w9kXMvXUhEdMhyYCvr4fDrmlvAHLuOV5ELbC2mNy+QEAPuF3hCWMrm84vIzIWYIt5ZzjzwW4q5HE9pMFywfVoE9l3uFFl5mX6fgM+I/7GM3sRKiXatePrOU5WSROWwyFtk5DbnROnBsp+FiXMPHC6JfUu0U/h/hhc32EhsSvSJ4YpQkCQtw+AyGGJ7nlXflToD95NL8UBIiL+JJ5Juad3UNv1u1V6zJz5NM3vbFMVbe6gFCmGnNdtT3tDm75NiHYPoPbIRhoIihjz7vPNgHgaGj9zrJkVl4SyY3TzyZD1xehXjypcLEQ6nxOlfN1x7p9dRQQ=,iv:SQmWhj+BC9r6gglyCq9Ro/LD+AvdxCNXN3ipYfFe30g=,tag:9EdmyEnEvfnsxmkT0+4j1w==,type:str]
sops:
  age:
    - recipient: age1ezazx7ck5002pq8qkla2lytrrtfq5hqn9xlwl7wc0ea43qjdle4sllf2g9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHN28zMW9Mamt3a1dTVEtR
        bTNmdFZONTZiV2pkNEo3cEFqME40UHkxNEJRCmZibjJHbmQzc0plYlVPbjJtVkxy
        ZXRvOWtWaEFVOExJeTFGeDJyNDR4YUEKLS0tIHFiaXhEYWI2d3puRURzaVlPa0Rs
        UkVzTDV2d051SFdub2VWVUhEc2hxZlEKC5QCxi4O/QlKsYqQRqJNqN5mrg3SvEgw
        OvGIYnbghFO4C+rmJtdzgGJz2iGVJrX+XGojbyrkXQLrdMd8Z4iu4A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-07T21:15:00Z"
  mac: ENC[AES256_GCM,data:EuQbd0/k8FuadSfdC2ETiT4GFtG+RpVDlJaajbhvoCNvNa2oySsPxLnr52AAorp1SRqfQkqiuwwTy5+Z5ddZpfpIr9cQugA6OR7V0DbdTjoj0SKKdZzXtUIIkvs46V5Biy//u4C3WdP638JjT9RcJDIsoSMwKr0pCGHm5v6a2ho=,iv:cqbm7QmmAQinpc/u7LuUvSLp5Te2hiPSFA1OXwrzHKI=,tag:8J/Ne8eFkTsN2YeBMXkNyQ==,type:str]
  encrypted_regex: ^(data|stringData|driver)$
  mac_only_encrypted: true
  version: 3.11.0
