apiVersion: v1
kind: Secret
metadata:
  name: truenas-iscsi-secret-config
stringData:
  driver-config-file.yaml: ENC[AES256_GCM,data:XSaqml+anP7etFRuGp4dTRmaXFJBVAWkjs5TOPJBnsQlsmqnS3mU0wY2CysJXFeoG5WAIIZA+QqGbED62V4wPO3PcF9vvCUa/qNKCVUp+ljC7XN51MSjNfMVi5ymIxSmnOHIH3TX3InF77PQ5FdweMoCAfc/SxVXn6pefZP06U2HRm6c41LAEGR9AEa72f05JCPXFPWp9MXsxglr4SW26rusm7RBOafqz3e38o4Mo114OcKYP1y35D24+YgQFAXUn9TiwPOJFpe2+0FBonIvEABM12Ba5fUf0uvBSmygVJ6yR/GytmOXRRhHAjHt2B/8UkuCqq5fXEYJGTfRW60s1rREUUJKfLaMCNNBEMrJD6yAZ9BqTnAZXKaaNCp8BP4QG3nf2YFkP4Z9KrdQUmBZwC6Z52glUtwbHMxO4ul1nqxoicOTpe/3/lqB4TYmmC12juRFXxopa3ayyIO8URHBeH7Wm1UWlVg+z7NCvz2d3h1OHza0QyqaEXmjzndRVhKpUzt0e4cZA5UWmI1HGrJvfY59fiYE5poe5gXvOEpso22f4/HE5CtcEeQs/topfOw27ILiyLf3BWtBB1sUMUJGpyOXoy2aTXdKbTT/YL49il6swS+tvY3BFcleWR8yIS+p+jVse3T9HnqEdBOuOlWKucbVv54YlwNszM4RmeAblaq3d2ODNYtvAvnI22vXIdVz4I56K1EOb4SARzp7GADy5lrIzXMy4pY34XEjoPX9Igl4vrCePh+FqzmQHLfVPl5tMlOgLen0h0UT85+OgBFbuwVWmJEDgbKn5uIr1x1hjF0cBLm8dcCyYVgu+rh844NIhrcG2vfwL/EnYsiXdqh074JuhOA/RtVaObSSK4HUc3tEw8c4ZLPLVtzCGLV0arxPEvGwWb95sXRdsfF6vCkmv82cfU3S/zPzQoNnhMG65H/VBK1Cn3aSwAH19m0Nck5JTxqRa/aEC9Fhg92eR6Fm8yNTxq4GPJ9jRJWqqdnLVWHKSjexARPk9arHGBRbukjm5ZkvICdu434mmsuR7wMrykvvD/bdolLF+C9t0TuBLmg=,iv:dTrg1lw37PYcQ7tow6w0/w/4432UY7csoV75KowQb3U=,tag:roVHdSanPJ/v0kfSgmljEg==,type:str]
sops:
  age:
    - recipient: age1ezazx7ck5002pq8qkla2lytrrtfq5hqn9xlwl7wc0ea43qjdle4sllf2g9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTTdtN01TZ1hjTnNhbmtC
        L256dmljRWpROTRMa0lMd0dTa0dMNXdXSWhZCjQ2SHdZQXorNG90dVFIeUgwMkFk
        T3lod2lxYVVlU1lhKzgrMG92d2J0YXMKLS0tIEYrK1F1RThadDM5UUlUZ0p4dWJC
        dGNEakxsTndKVlptclgzY2wxclNwRTAK5Nmv3dSz+6B11A0M42ejVlvBRu7tXMWY
        Ox24MzNat1BXvDZEOVTf6VXW0YdkDS4Mt1670SkRvDo3dBZiOdX6sQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-07T21:31:09Z"
  mac: ENC[AES256_GCM,data:cEKo5I+DPGUrkE2PAyVXmXfun6n6gMohtPKXpfrEB0HD8FkKEYkFLBWE17zj17cFGeEjtyI2cJQJBVon2wN4WbiwIZM3q0mrWE749DkOIr6KA1y8MGDgSbbxVL5tB3Os155f8ZPZkCo09xHqNcDhLrR/2LI/8qHC8GQ2D+iioX4=,iv:3aF3O+K95pjC7xmcxL8OcoidwBFhSg9ui9UGHWO2u7A=,tag:/A2WjNCLbN+ibjgPHjgWxQ==,type:str]
  encrypted_regex: ^(data|stringData|driver)$
  mac_only_encrypted: true
  version: 3.11.0
