---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: democratic-nfs
spec:
  interval: 1h
  path: ./kubernetes/apps/democratic-csi/nfs/app/
  # postBuild:
  #   substituteFrom:
  #     - name: cluster-secrets
  #       kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: democratic-csi
  wait: false
