# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
# renovate: datasource=docker depName=ghcr.io/siderolabs/installer
talosVersion: v1.11.3
# renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
kubernetesVersion: v1.34.2

clusterName: "chivel"
endpoint: https://10.1.0.6:6443

clusterPodNets:
  - "10.69.0.0/16"
clusterSvcNets:
  - "10.96.0.0/16"

additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "10.1.80.9"
  - "chivel.local"
additionalMachineCertSans: *sans

# Disable built-in Flannel to use Cilium
cniConfig:
  name: none

nodes: []
  # - hostname: "pi0"
  #   ipAddress: "10.1.0.20"
  #   installDisk: "/dev/sda"
  #   talosImageURL: factory.talos.dev/installer/fd348d98739b8a67b5ec9688914440959ef2446e2ad5cafdd839c9c356e40149
  #   controlPlane: true
  #   networkInterfaces:
  #     - deviceSelector:
  #         hardwareAddr: "4e:77:90:32:b3:e7"
  #       dhcp: false
  #       addresses:
  #         - "10.1.0.20/24"
  #       routes:
  #         - network: 0.0.0.0/0
  #           gateway: "10.1.0.1"
  #       mtu: 1500
  #       vip:
  #         ip: "10.1.0.6"

patches:
  - "@./global/machine-file.yaml"
  - "@./global/machine-kubelet.yaml"
  - "@./global/machine-network.yaml"
  - "@./global/machine-sysctls.yaml"
  - "@./global/machine-time.yaml"

controlPlane:
  patches:
    - "@./controller/machine-controller.yaml"

worker:
  patches:
    - "@./worker/machine-worker.yaml"
