---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rook-ceph

components:
  - ../../components/sops

# NOTE: Disable rook-ceph for now
resources: []
  # - ./namespace.yaml
  # - ./rook-ceph/ks.yaml
