apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:6w/DSJSE3Iv5tuSUi2N6NV+Z3dF7PCEHVFDwqP6yKr6pkmdb7MzKxw==,iv:0wjlxMNgsaoDU/pbVUmgDHdZV7Q0NaWzgQ+kvi0srWM=,tag:w4ooxmKz4ZrE+x+wKRH+Fw==,type:str]
sops:
  age:
    - recipient: age1ezazx7ck5002pq8qkla2lytrrtfq5hqn9xlwl7wc0ea43qjdle4sllf2g9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0dHZIZ2tyWUFwNTJqSGNv
        aTZra1FISElSeDdaVjdscXV2WjkxSU8vNDNBCjNOVWQvSXVIWVJ4QXFRQnprQnd0
        cDRtcW5DTmVoeE9WUEhQMDdaV1Y3ZW8KLS0tIFFJNTZucGwvMmErdFpJWllmSWFM
        ZlRBMEt5Y3dRM3NWTlJGeW03eXdCWWsKu/6qDrTRq6kpJv1Zinm9qRnqa3BhjiHT
        bekw0LQnJfG/BOTBkCTt6MOXLYICTa8MmGq3fJ2wNTfpqy+8HMf4zA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-16T21:09:25Z"
  mac: ENC[AES256_GCM,data:08t8zRN74n8uagveTgPMvg0SvonlHxRhKvuRsTiqk6whkcMaOcm37ocpGCqmslwvy2WDT+l/dznvlCuV6Wm0hqt7M4PWXiJM956U9DDTdS6lNuKvnNh7/jEj17XqsHYyuDREEMzA3x58bvVewOWagfMWVNaD5wmIgAPsrxHAmWY=,iv:BmKiZgME2CpKRbwkhXK9acxbv4YEv0IxU3rNJibC/hM=,tag://juc/oomnKVyWiFYv8wbw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
