apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:O9kT1a7gORZN,iv:KTC1wtcslpWoyGSS+LIh3iyn8492CxHvEnjXYxY5Y+Q=,tag:UT33hGBSqhX59vMz3bil/A==,type:str]
sops:
  age:
    - recipient: age1ezazx7ck5002pq8qkla2lytrrtfq5hqn9xlwl7wc0ea43qjdle4sllf2g9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYaWJVL0U0M29UdWJGQVZ4
        dHVDOCt5ZWNObGhycWF6K3FjYVk2QVMza21vCjVQaGZTbllyRFJaR2xuajlRc3k4
        Ry82enpFRVg2SWU5NE1JUU5FMDArdFEKLS0tIGtjWkg5WFdzSXdwRXA3cFdxUjhp
        MXl1ZU11blROenV1bDZwalJzWUUwNDQKoKncO5ZCxahRj9w8qeg8pRMfiKUiciY9
        CJl3tIXZv4nSq5vOSCW+EgRdRjebbSIh9LxPIWq+F+hhvCQu/drZLg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-16T21:16:31Z"
  mac: ENC[AES256_GCM,data:W/WsflJUQBT/o4Y3Kk2m8/z5jsfiyvPnMGCFXH1pcoH+Kof2JJbEuiDZdWEHDW0ld8/m/DVB3y5xM/g2ViySQ0y4p6LIgCwrtR/u4tKfO+OaTjv74DAT5kUxNKBEaP5MTXvTg2W3IF92iB6uF0A4YnIkNdDfm3CsEZXCz+kAnvc=,iv:+/hln2W/LgJjwIjFByEq3uUJijqWKHBeu/QoD2SnA4U=,tag:3oL8tcuYle8g5u0B3y3HLA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
