mqtt:
  enabled: False
cameras:
  dummy_camera: # <--- this will be changed to your actual camera later
    enabled: False
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:554/rtsp
          roles:
            - detect

ffmpeg:
  hwaccel_args: preset-vaapi

# Devices
detectors:
  coral:
    type: edgetpu
    device: pci
