---
apiVersion: v1
kind: Service
metadata:
  name: &name frigate
spec:
  selector:
    app: *name
  type: ClusterIP
  ports:
    - name: *name
      protocol: TCP
      port: 8971
      targetPort: 8971
