apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./podmonitor.yaml
  - ./grafanadashboard.yaml

configMapGenerator:
  - name: flux-grafana-dashboards
    files:
      - dashboards/control-plane.json
      - dashboards/cluster.json

configurations:
  - kustomizeconfig.yaml
