apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:VpS78OSU5hz/rHcLgnPYqlQWuj8qWOjxTza9CdN/MkG7ZWx0J4Y1p01eDs8xVNIakwQnCSKz7mmiBZCPdW4nKx9tyGka/sr/S+imm2i7kzfAxAcOfZjn9L/iWy1x2npkmr7NwEqjTr2wYyhRSKkEMxtT7RsvHt4Lm1QXkmOueCgaZXZPpAAyXpyaA5BsoxUKWQ9osGvBI4Lvaqvy3YusyIaV8avKpy6OO/TeZR8Iqvt6k7dT,iv:ceRCCZsTWyt6uy3LTjPiiNmjDOXqSDIWO6P4AZXGYxY=,tag:18Y5T29+D6BUZvVkNtX0gQ==,type:str]
sops:
  age:
    - recipient: age1ezazx7ck5002pq8qkla2lytrrtfq5hqn9xlwl7wc0ea43qjdle4sllf2g9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbmFobHdSWWEvbzNoUS82
        ckhML25hM2dLaDE2eEl1ZStGWXh0b1ptenljCncwS2k2UmprVmV6TENvVVM0akQ1
        QTR4czlNdTZlNUorOXdwYXZzYTFSUlUKLS0tIDkzdloraFB5VGNBVWpJeWViaitO
        UHdCWnNxU0tPOGI2aVJQL1gzbFhFN28K8T/AjVq9qBLSubsdiYuTh2LtZYCnxJfL
        J43IF2V/GCaGalAUSDORmKYEK9pihvifoZFlk8BbPPZlPjQiWc7Idg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-16T21:04:01Z"
  mac: ENC[AES256_GCM,data:c0tmbWzcn/ZhVo4UAfnpQkv6cMCTAWqOT64z+maj08cPr91leWlA5mnYNttXaSs7BMTdswDJ0XSKG7CiRQGwkYe0M7hhgR5wHUpNWSNYggbN09XqOv99fJXB4XhyPeRs8FIxzHQ+EM0RXDhSCP7M646jiGLmyEX08EV5knbMFHw=,iv:N1YPr0IiI9KLZvUmEmwMFFznLtnA/qgURybM5vdRoYw=,tag:vsItX32cFCp4tJTrN74RxA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
