apiVersion: v1
kind: Secret
metadata:
  name: unifi-dns-secret
stringData:
  api-key: ENC[AES256_GCM,data:mqhcA8zVxy7rA+Khs96sJ0YCpBJVzRixdO/PPxiShmI=,iv:DENn9v/Ba35bY/dGw1AibbjSCyk6SKwL3+za3wZ+eqs=,tag:rNDOWzEAN9W2X+e2JmD4xw==,type:str]
sops:
  age:
    - recipient: age1ezazx7ck5002pq8qkla2lytrrtfq5hqn9xlwl7wc0ea43qjdle4sllf2g9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOWTNXSlBrTmFUVWdodzZZ
        RE0rczVlZC9EQnpBSjlaazRNKzVyTkZzcmh3CjB2RGJLK3EyOFlMK2RZWVorVWVm
        K2diY1BYaThMQitIVWR1bG82M2F5Q28KLS0tIEx4TWtSblc1bU9QYUhGR2hnSFBR
        UGJmWnJFTko1dGtXcUxzVjR5QUs3V2MKR67FumqrN11lzk3bs58XHopU7zzczFZE
        Aqy9ZZP75VeLLaPg9LeWeSewoNeP2Zvc36maJv7Me1moNnM0kd9Xqw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-05T16:56:26Z"
  mac: ENC[AES256_GCM,data:f5xhNE006wU9QXu4xR3PU5OLdaSvzwxT9xAtUEoDJvbbmDealoRuvh5hPA63rNOYpuvwX+tfC1cnJyDI7h8BmqGpQ4+LckIlpU3Xaw40tn5DwsGkKeL2z+ZzDGwUhF93Mm3gjwM64GJ4OzxYpdE/f2urVzPoU6bBfVgBMlBfDf8=,iv:yYCMwIK5RINvn6SKFlVcXs8/gO8BnxFvR6aBmD5pcT4=,tag:m1LH5ppj7jIToxmtsxz3bQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
