apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:rPsKSi1hGVffZA1Plpo0YZTkCu+89x3qgmfEDCCzy8MDUp5n41MP9A==,iv:Y0VnCR08F/UAR+7jHoKr3Vi+ad76IQmOOBFs5aGuIos=,tag:mmS6qRwE8IM70F6amzdr1g==,type:str]
sops:
  age:
    - recipient: age1ezazx7ck5002pq8qkla2lytrrtfq5hqn9xlwl7wc0ea43qjdle4sllf2g9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQVQxVHR6aFYyT1hURXZn
        YWFkZU9kL3U0OUYzK0tVdGFCY25ZYS9aakhJCnlNM3dBWFREVWJxaFdjZlhQbVV4
        dzdibWp5dG1qajFQRzJ0THcrd2lubWMKLS0tIDJvUm1mWE5LdDREa0dnaWx1bFJJ
        TkZmT2xBamZRam5SSGpmci9Zeko4bjAKiBOKFAaSVuQ71bewd2QzfaK2csxtTi1g
        cPNxg1CZ1K+MiNcRtf73WnBtnjdUO9ZZBFRq4lMnLC2TfIDpsXX3AQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-16T21:08:52Z"
  mac: ENC[AES256_GCM,data:oWlsTh5RGXWCNK+7s/1OYq+clCwyL+eB8Xfq9r635SRQXOFssnMxkfFPr82J90FHn1bBU8WnQr6qzXNNtLcqrqxk+plRwLFDHnaCnE2wHAR00ukhs4Px5W5nepeP8ccaB/mV0rDH45CNLCCEbR5fXYCHjj3j2IfIamhw4D6sbCU=,iv:eH7kqxywnyvHxBjUFKqY9RnyJWNcpz6nWjksDoEMoLY=,tag:lUAbc385fnz0dQVajLnQiA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
