---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./certificate.yaml
  - ./certificate-production.yaml
  - ./envoy.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./podmonitor.yaml
