kind: HelmRelease
metadata:
  name: truenas-nfs
spec:
  values:
    driver:
      config:
        httpConnection:
          apiKey: ENC[AES256_GCM,data:3b4gQdMvnGdZ9Z4SFjQmTFIDzzKpv7mBKv9YAjEFSFXIkdVGEOMhAAYhG7jq4yGHYf22FN3e75XG5dToV/AikNev,iv:3OIYg1Gul8lJ5eIl3tiwSXQmkAm408r14dRQHttuE3c=,tag:vDfiI89uPhSiu9wmK49Dsw==,type:str]
sops:
  age:
    - recipient: age1ezazx7ck5002pq8qkla2lytrrtfq5hqn9xlwl7wc0ea43qjdle4sllf2g9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUjBsRFFWM0RhcmliUUIr
        aTVlbGwrSTdHTGR3RHpmVWdQNFFqZmdQam1nClBYZmxOWDBjVDFPQnpvbEJwVVFy
        LzVkVHEvQ1JOQzh2SUZTNXRlY0l6R0EKLS0tIDVDakdyaE9EL3cwYUpYcWViWCtQ
        WDFMaHMvMXRYSjFTb3VQUDdCckNGSkEKQysX6RSGdECbFf8JHQm1ov1vdvL/RQ3R
        bd4QWswzCQRESPQB6inA+KKtFcgeIvmGO7KkgGYoJA3Y6iZyjRjMbg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-07T17:07:30Z"
  mac: ENC[AES256_GCM,data:xWiSYOIyL0/kOlP4K0Z9tA+TDQWz2+SIWDQAPmb4TtCgyn/YTM7UbqgAzptVKGl1eZnVsGPDTMmsc+cdFZ1bIjtFtFTY9F7sfYRCA0CLxxP4Rft3k/8kPAAMOf0LSK9GZRVA3PiGr6tfg4hUTG2jlTNtGZTl4zxEURKQGioDvxg=,iv:rTgtyHZ1UgxE+OEKpE3Mie6xHz6zUjUbOQ+QWSwmE9E=,tag:9g+LlC1trxcHVCJP9WQQHQ==,type:str]
  encrypted_regex: ^(data|stringData|apiKey)$
  mac_only_encrypted: true
  version: 3.11.0
