kind: HelmRelease
metadata:
  name: truenas-nfs
spec:
  values:
    driver:
      config:
        httpConnection:
          apiKey: ENC[AES256_GCM,data:2OvvbgP2OpX2D+e+X97RrDUMGaxUOh6epAchrHfCxRUNvPLS7iLFvp2jb6LtW8Fl/4aRBd6UEEOVIq+ELUTJhOKB,iv:iRbGEzGvnXUvTU7YGz3e+3rbXC3Wo2gzUzAn0LcRAbM=,tag:kVb6dbY++Afvv5yAXgmU5w==,type:str]
        zfs:
          datasetParentName: ENC[AES256_GCM,data:dX5o+ihHfosl1ldE3JFVBRp+0z3X+6o=,iv:bU506xtC992pA0IKR2GQXImp6AYqeXnhnDFQ+sX50Yc=,tag:OCCciwYECSYb9DhYzZh63Q==,type:str]
          detachedSnapshotsDatasetParentName: ENC[AES256_GCM,data:sXETzk3gjv4UOppzVjMYNJApINccxQ==,iv:YOUVr3xhubDQvAz6kcbgV0R9MsDYPW8XFYclX91j/BY=,tag:sH2lSwpX98BAj3pf03Fhdg==,type:str]
sops:
  age:
    - recipient: age1ezazx7ck5002pq8qkla2lytrrtfq5hqn9xlwl7wc0ea43qjdle4sllf2g9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdVFZQ3FkRHBJM1NCb003
        NFZLTkl5MFU1ZUpjYWhDSXUyZ0Y4VDBnSVJFCjl0Z21hbWpoNncyVXVhSW5Lb0Jh
        NEVrdzFtUXV4clFrZWFWM2E0WlozUDgKLS0tIE1aeHY3bEFJTlM4d1cvbVJTTFB3
        MmFheGwxdko4V0ExWW0xZEtGdFE4ZTAKQVO/blasgxRCEJU5leRrg1TchfCJL6BQ
        PZzr+AJYHgLRSTYQlRRo6uzNZ2Aa106HQyZu1OhPFjdr8w637saZeg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-07T17:15:55Z"
  mac: ENC[AES256_GCM,data:kTlkkRUwXHbXcUTzvEwgT3Ek9m20k65N20KXogRfaqubIFC4ObCbPmvSnUYufJ557TpsHz1O0iFKr7hKXzHUR97H2maJT3z+GEuovjzlu66iJdr0MYB7owuLS9ZNTe6IvqwEfqRAgWeoVLCI+0V1KZH0DJtj07K6nW0S4k8/k4U=,iv:b6u7WWnx4FxAEJuJ0XLhRef7MOWmR7SYGi62+T7R2dI=,tag:8j3DE4fmUaWX4P6PoTsS5Q==,type:str]
  encrypted_regex: ^(data|stringData|driver)$
  mac_only_encrypted: true
  version: 3.11.0
