apiVersion: v1
kind: Secret
metadata:
  name: truenas-nfs-secret-config
stringData:
  driver-config-file.yaml: ENC[AES256_GCM,data:zYRSsJDv9OSeHpIaSf0dfrZMY/jwgOnI8tYuyo52l5mAJ53E7cmoRpVJBbr67pbgHJjgA6bAWzs0cYhegQz+0XS3DI2lQ3fiRffXYNCuVvqBGEfDDLmXIE6mHaTVkSD0TawHBWUBYzOpYJc5/qv3jNV0L6WCPYXCFkKEHz/oUdG1clB/z61HX5T89IeJiV7n3sQGOlZN1FuURlaukFOHyuuUrthWOdu8dbdTV/yIRdO5ixr66SlkUeQcev2UQlqi5sSYX1JFqZxTtC4D6gpm+sWKm7FcGg8KX/zvvYm8DqfPyhclKF1kbgRTe2WW5LE8O/6Gy8BabZh/tZWrU8Kt2EEIYKrRgC3XCWzG04I2h+K+DViqUvD1QrKirLgmAzr4vVFuQvsNGca3TtnCAiADY6fg+YlSHFqbjSk10QRNbJAq3FqsZGBLvuDjLFaXXv0P1CZlW2UEGEPgUgc5GuM1yfn1uhz1I/iSM0JXR+zGGyC+7Ik3hI6qZn4Nooud/ypHJ3aHHpEZ8MOrtL+sh8I6F4qBh8H8be93379fEdzfZOvC6/mIISBmb6mD+NB+axkYrgdQ/eVHjBeAAfDxlJlbcDN2ot7Vwa+8ySvFqyxZ8XKY632EDeYw49sudx1zKYDDSRMb1jVx9TQcH4weQov7Rf0CH0U+PNhLgWcRb93IGsO4lPPQj3Dlzcu8qys57noeLe+HNnx2wriaeXKtptlMNMDUWVyttAd7K+UF6ICSn2rzjiFBoIt+dSc3uK+qxzbRj4RWqUNs6Xi2P+2UFLhOcbj3EVwUBNd47iNeJJumidvp5xrfO5fh9KGUpRHtj+w5AmRGZeJhgURbz4pT/fNXbt6a1YAvD4dmgHUSgUAlfkWofy7RyZEE1o0v2E7NmIjRVb5cUnnO5rc88a8V4ydvNQFqwr4Maazi4SdIBnT1NetYG+tFqv+uOslJT5jEJAMc3PgwTLt0veDqMd6VuQ5E/p5fqdG1aWGiISlFoD3wGeGiUPWL2aYV/VWGjsCudvCPcvHzEMAqLmQb7h2F,iv:iTfDbjH89/zYt6iCC5gcy0xS/N4qWnXa2ELTj61j2oU=,tag:o2Sry9RYPbJzPKePPvHXpw==,type:str]
sops:
  age:
    - recipient: age1ezazx7ck5002pq8qkla2lytrrtfq5hqn9xlwl7wc0ea43qjdle4sllf2g9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsOWRoVmJuSThjWkxhbWdI
        M3ZkUitxNlpXZy9VODZOMWk4VDFPR1FuSmhzCkNObFdlUUVkSnRDN1ZObWRaM3FB
        NGNRNUY1aGFMM3grU1orZFhGZnVDNWsKLS0tIDRRdG04ajRsODJzRWNGWjBlUUM4
        dFgrM2NoZk0vbTR2dDBMV0NtNWtUeWsKherjFPbBfFqmbK1HNSGnnu9wazGskDCr
        qsQck9h2PKh2KnF3X4OVbPUiq5UkrXTY9a4cbewk9fWtGJowqc+rPA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-07T20:20:16Z"
  mac: ENC[AES256_GCM,data:0kd1OyfwKpsRUdG/hancyAgtRwLFVYhssrWiCceLsiqnpKk6oeKpDKv5EN2cpDAmo+7F0QLyzx0ddsxbrfM8eq2dfqohlC7pG7MB2f+YoUZ8YWl1ly6R2OplN3JuBDcGZ80S/7LuOBBgAyW3YslCOglWzGrHLiX2JYWNAAWTzWY=,iv:JhF80+uSD6DkyX8SgdUjRk0I1bpPlylGbxBWpANLKaU=,tag:Ldu9BSbEWgGFK5b/rXRkWA==,type:str]
  encrypted_regex: ^(data|stringData|driver)$
  mac_only_encrypted: true
  version: 3.11.0
