kind: HelmRelease
metadata:
  name: truenas-nfs
spec:
  values:
    driver:
      config:
        httpConnection:
          apiKey: ENC[AES256_GCM,data:n+05LALc4qPSV+ro7WNfc6fme7EUmm4VXPBfftzj8R72Vj94VetuEW+c76xc+U1AsSXqBK78GYBHiIyst4azVuWU,iv:ETiUPT7KEANUMOM4cdRbnaiJv9ErGwJjRwpuZjlhto4=,tag:adyWKB4jCxTT74d5rltDvQ==,type:str]
        zfs:
          datasetParentName: ENC[AES256_GCM,data:6YCZjzYz9jTgJwQXDAY9C+7/DPoHQcU=,iv:9GXeGEpX38GkegJGr+n2yWkyiFbOkdCv9HrOEIri6mk=,tag:UdeN1UFRKbHF3UYB+o47vg==,type:str]
          detachedSnapshotsDatasetParentName: ENC[AES256_GCM,data:doyIT9SgdJ6Sfjx7zYzKBIqtEtfJUA==,iv:KhDxb908oogaazwtw933DnOI82RTAgVAlMzpEIIwLi8=,tag:4taVb3AsOubKNIZO+81ncw==,type:str]
sops:
  age:
    - recipient: age1ezazx7ck5002pq8qkla2lytrrtfq5hqn9xlwl7wc0ea43qjdle4sllf2g9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjclBLTnFCZEVkRFdJMm0v
        b1p2NldlbTVvcURjd1hWRzZDdU1pS29JVVJjCklVVWxCRzJrbElIemtBa0tJOHdk
        RVZGclhmMm9xVnVKV2k4c3BpLzllcmMKLS0tIDFLVjNsbXJ5U3dabm1iUXkrQ2ww
        b0JuS1gyM2FSeGFBZUpuRVlBQllPRzgK8HNfbrPRogXTH8hMV4fn5zxLQcRWw1DB
        vjTIrRF9qFW/uvkXWPoIJkQIoE+G2WeGGM7sLhmwrmdiCqCGFPglVQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-07T17:32:54Z"
  mac: ENC[AES256_GCM,data:9VD+q/3JJwl+MoP6y6QIffDjuPfOhTwb8zJ/mY9AgxXLiA99lg931HeA6+XVhB3hEJb+uiHGns84xnW/UeyxGcXjJlStFc2/J4CniRGEw64ipQLSKg6HU81WG2qvO9s+JJNzOXDJ93+YACR0nCTJflABBuPV7e0Yh/k0CbQx1l4=,iv:cAO/5LuA4zRFEemfR7lmcmiHqPJJKjJbFEFmZAjp9CI=,tag:TXauHUm3kDmk95KVqEhvLw==,type:str]
  encrypted_regex: ^(data|stringData|driver)$
  mac_only_encrypted: true
  version: 3.11.0
