apiVersion: v1
kind: Secret
metadata:
  name: truenas-nfs-secret-config
stringData:
  driver-config-file.yaml: ENC[AES256_GCM,data:wgPemCOdkvuysNJ2oVikIrBEFnaGdWOsHygUB1UH9BAR7HrJ+BKHkkODoFlAgAUNb50Yp3ggrjRaX7BZh3ouzt4GGEr6498co4xNavsuLaNBBByfJzfYWoX1LoYxLi9nhy7Pjd0XuBmeeR4LVM4KxmLVENzO64LhjV3lA94ILiMaoIThgRwP5Oyq0MUy0f2U03kPVSVTuxEhkIGPHSAZHZ1WcsLdkgJK9qgbccJ4hwSzVEV6i0jv6+hNbF2JHD8bC5dEd1h6OsClbSFRlFZzomyMPXNRE9M8Ec8mUQlhDHVLzc+xmxw9Q5+Cka5E97px6fINbCmYKlVA0AbqowPYZvkdX4p1BsYbTougSsrTWQS3JToi3pLcyMiOyjFhozrpn8xA12Zmtjl20T8E1n7QyjwJVXHT1DmzRX51s7JiTgce61MevRFsdhwHBzRXXh/Ou2x9PYj1P6M2FDXEeF6lR/MA1c4iqig1iWW0UjdxqRRWLdIx8VTtlkAiyR2HzaeVS3YmuQkqN6c8lkAG2Yff2cW1bTxIdArHZWfdpIrYXszfOFCvmhu8kq+ZLat5hv1fil5+2hurgOo9YHc54KEw4xoLEebcstozM626caqvRFtKvAboVP1scx3QPxWqXzuEbswu9poh2ZfUmSe8JQAws4F6rU79uOMvHNq3bcqn17x19BO8s3RYajCv2vWmxWdrlnK6w2NnYEmSKQyEUQNK0ruIIVlJugfAJwGSzFfYIy/65bZPyaLoaGogo2S4d6juAM7XAckP2ocnO22azicQn0gQ75ojCHjWvCXyFaWzZSWBiWDc1nZDuEsTB8ndV+L6eKs4akjyMZmaBf49CPQSOZFhses6CERJPMqs8yLDQmM9/jKCkvlwluod1r0ojc8bYSp+2jRXBip+2HZr+Ku5gVeYKLo1v2dA4NIU66myQyVdCOQqRB2SEQqdrMopbJps3MK7A5PCWOsw44+kt7P8lJUzKG2/H2bD91TPCKKV1O3MBjQFWw2YRDdt/315wmLYGwVi52aJ6X2AWCa5,iv:aFK0dfxlmTF1Yszj0OvdLXQ9KfCXyRit9EtjEHoufWs=,tag:eW563+4+EE7K5HcyiCMZXw==,type:str]
sops:
  age:
    - recipient: age1ezazx7ck5002pq8qkla2lytrrtfq5hqn9xlwl7wc0ea43qjdle4sllf2g9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZXVFcCtsblpxUjJKQnRI
        S2FhNW81YnlnUnZRSGZJcFlEa1QvSmxpU0VnCmpUUUsvaHl1NklneldKeEQwd3Zp
        ZlZPSE9uSzI1M29yNE9aNW44d3VSdlkKLS0tIHYzQllNOERBb1JGK0VlVERseFJL
        bEV3N25GcjlLOWdJWUREdkM5Qjc5bVkKLuqrStq3kEp4x24aEZ5eJRUMzXdFlFFP
        Ue8DE515M5b/iZI6OMpshvJKkfds1aSwjEYOFgHQg38tKTpH5gc6Sw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-07T20:48:28Z"
  mac: ENC[AES256_GCM,data:XTNGrPsYNyobkcs0rCoWmMTMMyAPdAMGiALfWc6O+sPi8HeoB1PCvTVM7R+reekHpQyA7svS5kSTlx1xBW+flaAqhqBe6okuOr5o7BurdQIxXaoBwczNa1zaF/7Lhxdnenq8dgY1/NGy2Ik+mJhrTTcsJJKZIQn8MEGsZY0D7jM=,iv:ldVjfrVOGUJ9J24saM5mZlep/u/tJfvsJmDU3HOXBaM=,tag:BHCSgk95T4yVL7xLXp4G7w==,type:str]
  encrypted_regex: ^(data|stringData|driver)$
  mac_only_encrypted: true
  version: 3.11.0
