apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: flux-operator-dev
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: flux-operator
      app.kubernetes.io/name: flux-operator
  ingress:
    - ports:
        - protocol: TCP
          port: 8080
      from:
        - namespaceSelector: {}
  policyTypes:
    - Ingress
