---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./envoy.yaml
  - ./gatewayclass.yaml
  - ./envoyexternal.yaml
  - ./envoyinternal.yaml
  - ./backendtrafficpolicy.yaml
  - ./clienttrafficpolicy.yaml
  - ./httpredirect.yaml
