apiVersion: v1
kind: Secret
metadata:
  name: rook-ceph-dashboard-password
stringData:
  password: ENC[AES256_GCM,data:n3jom8j2l8U=,iv:ZZP7hPJG10OfTXVoiKuCwzZa4J+8cq3gX55uIloX1yg=,tag:vOcI0K4dg62AhvUTkpxShw==,type:str]
sops:
  age:
    - recipient: age1ezazx7ck5002pq8qkla2lytrrtfq5hqn9xlwl7wc0ea43qjdle4sllf2g9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUnpoVVFxSHg2S0hQcEll
        bzFMU0NwbzRxVTRqT1JGMnJldUVkclkyTWtrCldhSlVtaTN6MDE5ZmRiOHZWVFJS
        U1ZFWGF3NWU0cm05MGg4cElkc1VGYmsKLS0tIHZ4Wk1Uemg3eEJkYnl2cG9Hckll
        c1E2NnE5MmhqS2RzZVV4VkEwbWZZYnMKFMqJxMILRhmgjyc+CZJ0pldAk8Qp3Ble
        7EILSuGeevyUc5vy+KJ4BdWobZyu/Bq/1Ljo018VhIbu3QujrnmEdg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-05T17:24:27Z"
  mac: ENC[AES256_GCM,data:x/pLGEEC69kvBofw3m425jE13IAl5I3y78hpohu1K9lchH7kM4ToFKIepfGNcU14zbFC+xIYiX/ffw376Dg8a+Blqv4zTRIG3Z7gwdju3gqPm1oJOKvaLeI0SO6hCAj1cFxIVxv3as5IIzbSUjspvgulNnYwMrv979YwI9jleKk=,iv:DF2AQzt10qzXNm6eOPYvL6AMPlU/qjHzwD5n7CDmvkA=,tag:QtfP0zkRq/hfZf5WKW3K+w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
