---
# Allow all traffic in network namespace (for Envoy Gateway)
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-network-namespace
spec:
  description: "Allow all in network namespace"
  endpointSelector: {}
  ingress:
    - {}
  egress:
    - {}
